# Generated by Django 4.2.3 on 2023-07-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_app', '0002_remove_musclegroup_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.CharField(max_length=800),
        ),
    ]
